namespace Cirreum.Authentication.Configuration;

using Cirreum.AuthenticationProvider.Configuration;

public class ExternalAuthenticationSettings
	: AuthenticationProviderSettings<ExternalAuthenticationInstanceSettings>;